---
- name: Create wordpress database user
  mysql_user: name='{{wordpress_db_user}}' password='{{wordpress_db_pass}}' priv='*.*:ALL' state=present

- name: Create wordpress database
  mysql_db: name='{{wordpress_db_name}}' state=present

- name: Extract wordpress
  unarchive: src="https://wordpress.org/latest.tar.gz" 
    dest="/var/www/domains" 
    remote_src=yes
    owner=apache
    group=apache

- name: Set webroot permissions 
  command: '{{item.command}}'
  with_items:
    - { command: 'mv /var/www/domains/wordpress /var/www/domains/centos7.kern.net' }
    - { command: 'find /var/www/domains/centos7.kern.net -type d -exec chmod 0775 {} \; ' }
    - { command: 'find /var/www/domains/centos7.kern.net -type f -exec chmod 0664 {} \; ' }

