---
- name: Create wordpress database user
  mysql_user: name='{{ wordpress_db_user }}' password='{{ wordpress_db_pass }}' priv='*.*:ALL' state=present

  # this is going to fail as we have locked ourselves out of mysql
  # unless there's some way to specify a password
#- name: Download wordpress to vhost webroot
# wget: {{ wordpress_release }}  
