---
- name: Install MariaDB packages
  yum: name={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-libs
    - mariadb-server
    - php-mysql
    - MySQL-python

- name: Start MariaDB service
  service: name=mariadb state=started enabled=true

- name: Lock down root account from elsewhere
  mysql_user: name='root' password='{{mariadb_root_pw}}' host={{ item }} priv='*.*:ALL' state=present
  with_items:
    - { '127.0.0.1' }
    - { 'localhost' }
    - { '::1' }
    - { "{{ ansible_fqdn }}" }

- name: Copy over /root/.my.cnf credentials file
  template: src=dotmy.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Remove anonymous database users
  mysql_user:
    login_user: root
    login_password: 
    name: ''
    state: absent

- name: Remove 'test' database
  mysql_db: name='test' state=absent
