---
- hosts: centos
  become_method: sudo 
  become: true

  tasks:
    - name: install httpd
      yum: name=httpd update_cache=yes state=latest
      
    - name: start and enable httpd
      service: name=httpd state=started enabled=true


