---
- hosts: centos

  become_method: sudo 
  become: true

  tasks:
    - name: Edit dircolors to 34 instead of 35
      replace: dest=/etc/dircolors regexp='DIR 01;35' replace='DIR 01;34'

# could use lineinfile module apparently too?
# have a look

