---
- name: Install (default) php packages
  yum: name={{item}} state=latest
  with_items:
    - php
    - php-cli
    - php-common
    - php-mysql
    - php-gd
    - php-xml

  notify:
    - restart httpd

